name: alignme_pose
description: "Yoga pose correction"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # --- CORE FEATURES ---
  camera: ^0.11.0+2           # To see the user
  google_mlkit_pose_detection: ^0.12.0 # To detect the skeleton
  flutter_tts: ^4.2.0         # To give voice commands
  permission_handler: ^11.3.1 # To ask "Can I use your camera?"
  url_launcher: ^6.3.2        # NEW: To open YouTube video tutorials

  # --- UI HELPERS ---
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2     # For beautiful animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # --- ASSETS SECTION ---
  # This tells Flutter to look inside your "assets" folder for images
  assets:
    - assets/